### PR TITLE
Improve a bit

### PR DESCRIPTION
**Pull request by Shougo**
I have improved the pattern a bit.
I think it is better.

And I have removed min_pattern_length.  It is not used.

### CODE REVIEW

**Comment by tbodt** [comment]
Why would it be better to trigger tabnine even on whitespace?

**Comment by Shougo** [comment]
OK.  I have improved the pattern.

**Comment by Shougo** [comment]
@tbodt What do you think the pattern?

**Comment by tbodt** [comment]
\S* works well for me.

**Comment by Shougo** [comment]
OK.

**Pull request closed without merging**
