### PR TITLE
Add protocol 1.0.0 support

### LINKED ISSUE #11: Protocol 1.0 support
https://github.com/zxqfl/TabNine/issues/30

I will add the feature later.

### LINKED ISSUE #13: Does not replace the word starting with number.
For example,  typing "20", then selecting item "2018" according to completion items;  instead of "2018", the result is "202018".

### PR DESCRIPTION
**Pull request by Shougo**
I have added protocol 1.0.0 support for deplete-tabnine.

Please test it.

Fix #11
Fix #13

### CODE REVIEW

**Comment by Shougo** [comment]
I have improved `get_complete_position()` implementation.

**Comment by Shougo** [comment]
@tbodt Ping.  I have tested it some days and it seems good.

**Comment by tbodt** [comment]
Seems good then, thanks for contributing this!

**Comment by Shougo** [comment]
Thank you!

**Pull request merged**
