### PR TITLE
Fix #14 TabNine:: completion

### LINKED ISSUE #14: Not getting semantic completion with solargraph
Hi, I'm guessing I'm doing something wrong.

Today I installed the plugin via `Plug` and opened a ruby file. I can see `[TN]` showing up in deoplete but it's not `solargraph` data. `autozimu/LanguageClient-neovim` seems to get solargraph data, so that should not be the issue. Maybe I'm missing some configuration steps?

I haven't purchased a license yet —and honestly I have no idea where I'd have to put it—, but given that there was a free tier I thought it'd work.

This is my Deoplete config:
```vim
let g:deoplete#auto_complete_delay = 100
let g:deoplete#enable_at_startup = 1

call deoplete#custom#source('ultisnips', 'matchers', ['matcher_fuzzy'])
call deoplete#custom#source('ultisnips', 'rank', 1000)
call deoplete#custom#source('syntax', 'rank', 100)
```

### PR DESCRIPTION
**Pull request by Shougo**
Fix `TabNine::sem` problem after protocol 1.0 feature is enabled.

### CODE REVIEW

**Comment by iovis** [comment]
Testing

**Comment by iovis** [comment]
Out of the box not seeing solargraph data.

Trying to run `:TabNine::sem` in the command prompt gives me: `E492: Not an editor command: TabNine::sem`

**Comment by Shougo** [comment]
Please try input the text on the buffer instead.

**Comment by Shougo** [comment]
Please read it carefully.

https://tabnine.com/semantic

It does not say type `TabNine::sem` in the command line.

**Comment by iovis** [comment]
Oh... that works! Sorry, I didn't realize it meant to _literally_ type it in the buffer.

Thank you!
screenshot 2018-12-17 at 14 28 46

**Review by iovis — APPROVED** [review]

**Comment by Shougo** [comment]
:-)

**Comment by jaydorsey** [comment]
I tested this on my machine too. This fixes the issue

nvim 0.3.1, latest tabnine, latest plugin versions

**Comment by tbodt** [comment]
Huh why wouldn't the combination of min_pattern_length and `[^\w\s]` not already detect TabNine::? Since : matches `[^\w\s]` and any letter would trigger min_pattern_length. @Shougo

**Comment by Shougo** [comment]
Because, `min_pattern_length` is 1.

For example, `TabNine::version|` matches `|` position.
It is 0 length match completion.
If `min_pattern_length` is 1, it will be ignored.

`input_pattern` ignores `min_pattern_length`.  So it works.

**Comment by Shougo** [comment]
@tbodt Ping.

**Comment by tbodt** [comment]
Why is `TabNine::version|` a 0 length match?

**Comment by Shougo** [comment]
match length is calculated by tabnine's result.
If `TabNine::version` matches `TabNine::|version` position, deoplete-tabnine works without the change.
The special command seems matches at the end of input.
Please ask it for tabnine's author.
It is tabnine's feature.

**Comment by tbodt** [comment]
I don't really understand the min_pattern_length and input_pattern settings. All I know is TabNine is intended to be refreshed on every keystroke; what settings are needed for that?

**Comment by Shougo** [comment]
> I don't really understand the min_pattern_length and input_pattern settings. All I know is TabNine is intended to be refreshed on every keystroke; what settings are needed for that?

If so, you should set `min_pattern_length` is 0.
`min_pattern_length` is minimum matched length to complete position.
If it is 1, the end of input matches are ignored.

But I think `min_pattern_length` should be customized by user.
I have customized `min_pattern_length` to 2.
`TabNine::version` is special case.  So `min_pattern_length` should be ignored by `input_pattern`.

**Comment by tbodt** [comment]
OK, I'll merge this. I'll also test with min_pattern_length = 0 and see if that's better.

**Comment by Shougo** [comment]
Thank you!

**Pull request merged**
